name: Deploy React + TypeScript (Vite) from main to GitHub Pages

on:
  workflow_dispatch:  # אפשרות להרצה ידנית

permissions:
  contents: write  # נדרש כדי לדחוף ל-gh-pages

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ קבלת הקוד מ-branch main
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # לוקח את כל הקוד מ-main

      # 2️⃣ התקנת Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # 3️⃣ התקנת התלויות
      - name: Install dependencies
        run: npm install

      # 4️⃣ עדכון vite.config.ts (base path)
      - name: Update Vite base path
        run: |
          sed -i "s|base: .*|base: '/Ihulan-cover/',|" vite.config.ts

      # 5️⃣ בניית הפרויקט
      - name: Build project
        run: npm run build

      # 6️⃣ פרסום ל-gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          destination_branch: gh-pages  # אפשר גם project-deploy אם רוצים branch נפרד
